### ISSUE TITLE
co-authors config file format

### ISSUE THREAD

**Issue by oshdev** [tamj0rd2/coauthor-select#1]
Thought I'd suggest a different format - a name followed by email in chevrons, e.g. `Osh <osh@evil.corp>`

The benefit would be that you can grab it by line and use it exactly as it is, rather than processing a JSON. I don't see a need to have separation between name and email, cause the only usages I can think of:
1. to add new committer
2. to search (just partial match across entire thing?)
3. to select and apply - simple, no need to build the string!

A complety unrelevant point I use a different tool that's using this format already (conventional commits plugin for JetBrains IDE: https://github.com/lppedd/idea-conventional-commit) that's using this format and if you can specify a file with the config, then we could make it cross-operable, i.e. reuse the file.

**Comment by tamj0rd2** [comment]
I've changed `authors.json` to `.coauthors` and its contents look like [this](https://github.com/tamj0rd2/coauthor-select/blob/25be146423319edf832633b9410342a0f6ee1fc4/example/.coauthors)

The behaviour of the interactive prompt and the pairs.json file has stayed as-is

- if you're using the interactive prompt, select a name from the list
- if you're committing through the IDE, either add the co-author to the commit message manually, via an IDE plugin or by adding your pair's name into pairs.json.
